# Generated by Django 5.0.4 on 2024-04-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='message',
        ),
    ]
