# Generated by Django 5.0.4 on 2024-04-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='SendMessage',
        ),
    ]
